export const IMAGE_ASSETS = {
  aiNavigator: '/assets/hud/ai-navigator.webp',
  playerPortrait: '/assets/hud/player-portrait.webp',
  yuutaDialogue: '/assets/avg/yuuta-dialogue.webp',
  whitePriestessDialogue: '/assets/avg/white-priestess-dialogue.webp',
  palaceFarBackground: '/assets/maps/white_palace_far_bg.webp',
  palaceMidBackground: '/assets/maps/white_palace_mid_bg_loop.webp',
  palaceSky: '/assets/maps/white_palace_sky.webp',
  stageSelectBackground: '/assets/maps/white_palace_stage_select.webp',
  emeraldSanctuaryStageSelect: '/assets/maps/emerald_sanctuary_stage_select.webp',
  ceruleanDepthsStageSelect: '/assets/maps/cerulean_depths_stage_select.webp',
  frostveilPeaksStageSelect: '/assets/maps/frostveil_peaks_stage_select.webp',
  emberfallCalderaStageSelect: '/assets/maps/emberfall_caldera_stage_select.webp',
  abyssalHollowStageSelect: '/assets/maps/abyssal_hollow_stage_select.webp',
  checkpoint: '/assets/props/white_palace_checkpoint.webp',
  goalIdle: '/assets/props/white_palace_goal_idle.webp',
  resultStandee: '/assets/results/yuuta-stage-result-standee.webp',
  titleBackground: '/assets/title/project-almost-title-background.webp',
  enemyGuardDeath: '/assets/sprites/enemy_guard_death/sheet-transparent.webp',
  enemyGuardWalk: '/assets/sprites/enemy_guard_walk/sheet-transparent.webp',
  bossPriestessCast: '/assets/sprites/boss_priestess_cast/sheet-transparent.webp',
  bossPriestessDeath: '/assets/sprites/boss_priestess_death/sheet-transparent.webp',
  bossPriestessHurt: '/assets/sprites/boss_priestess_hurt/sheet-transparent.webp',
  playerAttack: '/assets/sprites/player_attack/sheet-transparent.webp',
  playerCrouch: '/assets/sprites/player_crouch/sheet-transparent.webp',
  playerDeath: '/assets/sprites/player_death/sheet-transparent.webp',
  playerHurt: '/assets/sprites/player_hurt/sheet-transparent.webp',
  playerIdle: '/assets/sprites/player_idle/sheet-transparent.webp',
  playerJump: '/assets/sprites/player_jump/sheet-transparent.webp',
  playerRun: '/assets/sprites/player_run/sheet-transparent.webp',
  palaceTiles: '/assets/tiles/white_palace_platform_tiles.webp',
} as const

export const MUSIC_ASSETS = {
  title: '/assets/audio/titlescreen.mp3',
  result: '/assets/audio/game_result.mp3',
  world01Bgm: '/assets/audio/world01_bgm.mp3',
  world01Boss: '/assets/audio/world01_boss.mp3',
  world01Map: '/assets/audio/world01_map.mp3',
  world02Bgm: '/assets/audio/world02_bgm.mp3',
  world02Boss: '/assets/audio/world02_boss.mp3',
  world02Map: '/assets/audio/world02_map.mp3',
  world03Bgm: '/assets/audio/world03_bgm.mp3',
  world03Boss: '/assets/audio/world03_boss.mp3',
  world03Map: '/assets/audio/world03_map.mp3',
  world04Bgm: '/assets/audio/world04_bgm.mp3',
  world04Boss: '/assets/audio/world04_boss.mp3',
  world04Map: '/assets/audio/world04_map.mp3',
  world05Bgm: '/assets/audio/world05_bgm.mp3',
  world05Boss: '/assets/audio/world05_boss.mp3',
  world05Map: '/assets/audio/world05_map.mp3',
  world06Bgm: '/assets/audio/world06_bgm.mp3',
  world06Boss: '/assets/audio/world06_boss.mp3',
  world06Map: '/assets/audio/world06_map.mp3',
} as const

export const SFX_ASSETS = {
  'ui-move': '/assets/audio/sfx/ui-move.wav',
  'ui-confirm': '/assets/audio/sfx/ui-confirm.wav',
  'ui-back': '/assets/audio/sfx/ui-back.wav',
  'armor-step': '/assets/audio/sfx/armor-step.wav',
  hit: '/assets/audio/sfx/hit.wav',
  coin: '/assets/audio/sfx/coin.wav',
  death: '/assets/audio/sfx/death.wav',
  checkpoint: '/assets/audio/sfx/checkpoint.wav',
  goal: '/assets/audio/sfx/goal.wav',
} as const

export type MusicTrack = keyof typeof MUSIC_ASSETS
